name: Push-to-EC2
# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Build and Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use your project's Node.js version

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build project
        run: npm run build
        # IMPORTANT: After this step, your built site is in the 'dist' folder.

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          # The source directory on the runner, after the build is complete.
          SOURCE: "dist/"
          # The target directory on the EC2 instance.
          TARGET: "/var/www/html"
          # This option clears the target directory before copying, ensuring a clean deploy.
          ARGS: "--delete"
